inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120
